backend:
  name: github
  repo: alaqeela14/mishkat-new
  branch: main
  base_url: https://sveltia-cms-auth.alaqeelafoundation.workers.dev
  auth_endpoint: auth

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "articles"
    label: "المقالات"
    files:
      - name: "articles-list"
        label: "قائمة المقالات"
        file: "articles.json"
        fields:
          - label: "قائمة المقالات"
            name: "items"
            widget: "list"
            summary: "{{fields.title_ar}} ({{fields.category}})"
            fields:
              - { label: "التصنيف", name: "category", widget: "select", options: ["مقالات ورؤى", "أهل البيت", "وعي مجتمعي", "رؤى وحلول", "قضايا معاصرة", "حوارات ومقابلات", "شبهات وردود", "التوجيهات الأخلاقية"] }
              - { label: "التاريخ", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
              - { label: "اسم الكاتب (عربي)", name: "author_ar", widget: "string" }
              - { label: "اسم الكاتب (إنجليزي)", name: "author_en", widget: "string", required: false }
              - { label: "اسم الكاتب (فارسي)", name: "author_fa", widget: "string", required: false }
              - { label: "🇸🇦 العنوان (عربي)", name: "title_ar", widget: "string" }
              - { label: "🇬🇧 Title (English)", name: "title_en", widget: "string", required: false }
              - { label: "🇮🇷 عنوان (فارسی)", name: "title_fa", widget: "string", required: false }
              - { label: "🇸🇦 المقتطف (عربي)", name: "excerpt_ar", widget: "text" }
              - { label: "🇬🇧 Excerpt (English)", name: "excerpt_en", widget: "text", required: false }
              - { label: "🇮🇷 چکیده (فارسی)", name: "excerpt_fa", widget: "text", required: false }
              - { label: "🇸🇦 نص المقال (عربي)", name: "body_ar", widget: "markdown", required: false }
              - { label: "🇬🇧 Article Body (English)", name: "body_en", widget: "markdown", required: false }
              - { label: "🇮🇷 متن مقاله (فارسی)", name: "body_fa", widget: "markdown", required: false }